/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumber, BytesLike, Signer, utils } from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface IContentStoreInterface extends utils.Interface {
  functions: {};

  events: {
    "NewChecksum(bytes32,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewChecksum"): EventFragment;
}

export interface NewChecksumEventObject {
  checksum: string;
  contentSize: BigNumber;
}
export type NewChecksumEvent = TypedEvent<
  [string, BigNumber],
  NewChecksumEventObject
>;

export type NewChecksumEventFilter = TypedEventFilter<NewChecksumEvent>;

export interface IContentStore extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IContentStoreInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "NewChecksum(bytes32,uint256)"(
      checksum?: PromiseOrValue<BytesLike> | null,
      contentSize?: null
    ): NewChecksumEventFilter;
    NewChecksum(
      checksum?: PromiseOrValue<BytesLike> | null,
      contentSize?: null
    ): NewChecksumEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
