/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumber, BytesLike, Signer, utils } from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface IFileDirectoryInterface extends utils.Interface {
  functions: {};

  events: {
    "FileCreated(string,bytes32,uint256,string,string)": EventFragment;
    "FileDeleted(string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "FileCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FileDeleted"): EventFragment;
}

export interface FileCreatedEventObject {
  filename: string;
  checksum: string;
  size: BigNumber;
  contentType: string;
  contentEncoding: string;
}
export type FileCreatedEvent = TypedEvent<
  [string, string, BigNumber, string, string],
  FileCreatedEventObject
>;

export type FileCreatedEventFilter = TypedEventFilter<FileCreatedEvent>;

export interface FileDeletedEventObject {
  filename: string;
}
export type FileDeletedEvent = TypedEvent<[string], FileDeletedEventObject>;

export type FileDeletedEventFilter = TypedEventFilter<FileDeletedEvent>;

export interface IFileDirectory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IFileDirectoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "FileCreated(string,bytes32,uint256,string,string)"(
      filename?: PromiseOrValue<string> | null,
      checksum?: PromiseOrValue<BytesLike> | null,
      size?: null,
      contentType?: null,
      contentEncoding?: null
    ): FileCreatedEventFilter;
    FileCreated(
      filename?: PromiseOrValue<string> | null,
      checksum?: PromiseOrValue<BytesLike> | null,
      size?: null,
      contentType?: null,
      contentEncoding?: null
    ): FileCreatedEventFilter;

    "FileDeleted(string)"(
      filename?: PromiseOrValue<string> | null
    ): FileDeletedEventFilter;
    FileDeleted(
      filename?: PromiseOrValue<string> | null
    ): FileDeletedEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
