/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FileDirectory } from "./FileDirectory";
export type { IFileDirectory } from "./IFileDirectory";
