"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IFileDirectory__factory = exports.FileDirectory__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var FileDirectory__factory_1 = require("./FileDirectory__factory");
Object.defineProperty(exports, "FileDirectory__factory", { enumerable: true, get: function () { return FileDirectory__factory_1.FileDirectory__factory; } });
var IFileDirectory__factory_1 = require("./IFileDirectory__factory");
Object.defineProperty(exports, "IFileDirectory__factory", { enumerable: true, get: function () { return IFileDirectory__factory_1.IFileDirectory__factory; } });
