"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IDirectory__factory = exports.Directory__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var Directory__factory_1 = require("./Directory__factory");
Object.defineProperty(exports, "Directory__factory", { enumerable: true, get: function () { return Directory__factory_1.Directory__factory; } });
var IDirectory__factory_1 = require("./IDirectory__factory");
Object.defineProperty(exports, "IDirectory__factory", { enumerable: true, get: function () { return IDirectory__factory_1.IDirectory__factory; } });
