/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FileStore__factory } from "./FileStore__factory";
export { IFileStore__factory } from "./IFileStore__factory";
