"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IContentStore__factory = exports.ContentStore__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ContentStore__factory_1 = require("./ContentStore__factory");
Object.defineProperty(exports, "ContentStore__factory", { enumerable: true, get: function () { return ContentStore__factory_1.ContentStore__factory; } });
var IContentStore__factory_1 = require("./IContentStore__factory");
Object.defineProperty(exports, "IContentStore__factory", { enumerable: true, get: function () { return IContentStore__factory_1.IContentStore__factory; } });
