/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IChunkStore,
  IChunkStoreInterface,
} from "../../ChunkStore.sol/IChunkStore";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "checksum",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "size",
        type: "uint256",
      },
    ],
    name: "NewChunk",
    type: "event",
  },
];

export class IChunkStore__factory {
  static readonly abi = _abi;
  static createInterface(): IChunkStoreInterface {
    return new utils.Interface(_abi) as IChunkStoreInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IChunkStore {
    return new Contract(address, _abi, signerOrProvider) as IChunkStore;
  }
}
