"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IChunkStore__factory = exports.ChunkStore__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ChunkStore__factory_1 = require("./ChunkStore__factory");
Object.defineProperty(exports, "ChunkStore__factory", { enumerable: true, get: function () { return ChunkStore__factory_1.ChunkStore__factory; } });
var IChunkStore__factory_1 = require("./IChunkStore__factory");
Object.defineProperty(exports, "IChunkStore__factory", { enumerable: true, get: function () { return IChunkStore__factory_1.IChunkStore__factory; } });
