/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ChunkStore__factory } from "./ChunkStore__factory";
export { IChunkStore__factory } from "./IChunkStore__factory";
