"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.SSTORE2__factory = exports.Ownable2Step__factory = exports.Ownable__factory = exports.Bytecode__factory = exports.fileStoreSol = exports.fileDirectorySol = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.fileDirectorySol = __importStar(require("./FileDirectory.sol"));
exports.fileStoreSol = __importStar(require("./FileStore.sol"));
var Bytecode__factory_1 = require("./Bytecode__factory");
Object.defineProperty(exports, "Bytecode__factory", { enumerable: true, get: function () { return Bytecode__factory_1.Bytecode__factory; } });
var Ownable__factory_1 = require("./Ownable__factory");
Object.defineProperty(exports, "Ownable__factory", { enumerable: true, get: function () { return Ownable__factory_1.Ownable__factory; } });
var Ownable2Step__factory_1 = require("./Ownable2Step__factory");
Object.defineProperty(exports, "Ownable2Step__factory", { enumerable: true, get: function () { return Ownable2Step__factory_1.Ownable2Step__factory; } });
var SSTORE2__factory_1 = require("./SSTORE2__factory");
Object.defineProperty(exports, "SSTORE2__factory", { enumerable: true, get: function () { return SSTORE2__factory_1.SSTORE2__factory; } });
