/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface FileReaderInterface extends utils.Interface {
  functions: {
    "readBytes(uint256,address[])": FunctionFragment;
    "readBytes(address[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "readBytes(uint256,address[])"
      | "readBytes(address[])"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "readBytes(uint256,address[])",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "readBytes(address[])",
    values: [PromiseOrValue<string>[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "readBytes(uint256,address[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "readBytes(address[])",
    data: BytesLike
  ): Result;

  events: {};
}

export interface FileReader extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FileReaderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    "readBytes(uint256,address[])"(
      size: PromiseOrValue<BigNumberish>,
      pointers: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<[string] & { data: string }>;

    "readBytes(address[])"(
      pointers: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<[string] & { data: string }>;
  };

  "readBytes(uint256,address[])"(
    size: PromiseOrValue<BigNumberish>,
    pointers: PromiseOrValue<string>[],
    overrides?: CallOverrides
  ): Promise<string>;

  "readBytes(address[])"(
    pointers: PromiseOrValue<string>[],
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    "readBytes(uint256,address[])"(
      size: PromiseOrValue<BigNumberish>,
      pointers: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<string>;

    "readBytes(address[])"(
      pointers: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    "readBytes(uint256,address[])"(
      size: PromiseOrValue<BigNumberish>,
      pointers: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "readBytes(address[])"(
      pointers: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    "readBytes(uint256,address[])"(
      size: PromiseOrValue<BigNumberish>,
      pointers: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "readBytes(address[])"(
      pointers: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
