/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumber, BytesLike, Signer, utils } from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface IChunkStoreInterface extends utils.Interface {
  functions: {};

  events: {
    "NewChunk(bytes32,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewChunk"): EventFragment;
}

export interface NewChunkEventObject {
  checksum: string;
  size: BigNumber;
}
export type NewChunkEvent = TypedEvent<
  [string, BigNumber],
  NewChunkEventObject
>;

export type NewChunkEventFilter = TypedEventFilter<NewChunkEvent>;

export interface IChunkStore extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IChunkStoreInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "NewChunk(bytes32,uint256)"(
      checksum?: PromiseOrValue<BytesLike> | null,
      size?: null
    ): NewChunkEventFilter;
    NewChunk(
      checksum?: PromiseOrValue<BytesLike> | null,
      size?: null
    ): NewChunkEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
